"""initial_schema

Revision ID: 23a655966954
Revises: 
Create Date: 2025-12-21 17:50:06.501630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23a655966954'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporate_actions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('announcement_date', sa.Date(), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('ratio', sa.Float(), nullable=True),
    sa.Column('dividend_amount', sa.Float(), nullable=True),
    sa.Column('dividend_currency', sa.String(length=3), nullable=True),
    sa.Column('target_ticker', sa.String(length=20), nullable=True),
    sa.Column('acquirer_ticker', sa.String(length=20), nullable=True),
    sa.Column('cash_component', sa.Float(), nullable=True),
    sa.Column('stock_component', sa.Float(), nullable=True),
    sa.Column('new_ticker', sa.String(length=20), nullable=True),
    sa.Column('new_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('extra_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corporate_actions_effective_date'), 'corporate_actions', ['effective_date'], unique=False)
    op.create_index(op.f('ix_corporate_actions_ticker'), 'corporate_actions', ['ticker'], unique=False)
    op.create_table('delivery_logs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('delivery_type', sa.String(length=20), nullable=False),
    sa.Column('destination_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload_summary', sa.Text(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('billing_email', sa.String(length=255), nullable=True),
    sa.Column('tier', sa.String(length=50), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('tier', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('custom_data_sources',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('owner_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('field_mapping', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('securities_count', sa.Integer(), nullable=False),
    sa.Column('last_synced', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_data_sources_owner_id'), 'custom_data_sources', ['owner_id'], unique=False)
    op.create_table('email_subscriptions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('owner_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('recipients', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('schedule_time', sa.String(length=10), nullable=True),
    sa.Column('schedule_day', sa.Integer(), nullable=True),
    sa.Column('index_ids', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('include_attachments', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization_invitations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('invited_by_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_invitations_token'), 'organization_invitations', ['token'], unique=True)
    op.create_table('organization_memberships',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.UUID(as_uuid=False), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=False)
    op.create_table('report_templates',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('owner_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('report_type', sa.String(length=20), nullable=False),
    sa.Column('is_system_template', sa.Boolean(), nullable=False),
    sa.Column('show_logo', sa.Boolean(), nullable=False),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('header_text', sa.String(length=255), nullable=True),
    sa.Column('footer_text', sa.String(length=255), nullable=True),
    sa.Column('sections', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('primary_color', sa.String(length=7), nullable=False),
    sa.Column('secondary_color', sa.String(length=7), nullable=False),
    sa.Column('font_family', sa.String(length=100), nullable=False),
    sa.Column('custom_css', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sftp_destinations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('owner_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('private_key', sa.Text(), nullable=True),
    sa.Column('remote_path', sa.String(length=500), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('schedule_time', sa.String(length=10), nullable=True),
    sa.Column('schedule_day', sa.Integer(), nullable=True),
    sa.Column('index_ids', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('file_format', sa.String(length=20), nullable=False),
    sa.Column('include_history', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_delivery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webhook_endpoints',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('owner_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('secret_key', sa.String(length=255), nullable=True),
    sa.Column('headers', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('events', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('index_ids', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('retry_delay_seconds', sa.Integer(), nullable=False),
    sa.Column('total_deliveries', sa.Integer(), nullable=False),
    sa.Column('successful_deliveries', sa.Integer(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activities',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('activity_type', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.String(length=100), nullable=True),
    sa.Column('target_name', sa.String(length=255), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_created_at'), 'activities', ['created_at'], unique=False)
    op.create_table('custom_securities',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('data_source_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('ticker', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('avg_volume', sa.Float(), nullable=True),
    sa.Column('free_float', sa.Float(), nullable=True),
    sa.Column('pe_ratio', sa.Float(), nullable=True),
    sa.Column('pb_ratio', sa.Float(), nullable=True),
    sa.Column('dividend_yield', sa.Float(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('earnings', sa.Float(), nullable=True),
    sa.Column('custom_fields', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['custom_data_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_securities_data_source_id'), 'custom_securities', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_custom_securities_ticker'), 'custom_securities', ['ticker'], unique=False)
    op.create_table('indices',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('owner_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('identifier', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('weighting_method', sa.String(length=50), nullable=False),
    sa.Column('rebalance_frequency', sa.String(length=50), nullable=False),
    sa.Column('base_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('base_value', sa.Float(), nullable=False),
    sa.Column('min_market_cap', sa.Float(), nullable=True),
    sa.Column('min_avg_volume', sa.Float(), nullable=True),
    sa.Column('max_components', sa.Integer(), nullable=False),
    sa.Column('countries', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('sectors', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('max_weight', sa.Float(), nullable=True),
    sa.Column('max_sector_weight', sa.Float(), nullable=True),
    sa.Column('max_country_weight', sa.Float(), nullable=True),
    sa.Column('custom_rules', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('last_calculated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indices_identifier'), 'indices', ['identifier'], unique=True)
    op.create_index(op.f('ix_indices_owner_id'), 'indices', ['owner_id'], unique=False)
    op.create_index(op.f('ix_indices_project_id'), 'indices', ['project_id'], unique=False)
    op.create_table('project_memberships',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('added_by_id', sa.UUID(as_uuid=False), nullable=True),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backtests',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('index_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('initial_value', sa.Float(), nullable=False),
    sa.Column('benchmark_ticker', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('final_value', sa.Float(), nullable=True),
    sa.Column('total_return', sa.Float(), nullable=True),
    sa.Column('annualized_return', sa.Float(), nullable=True),
    sa.Column('volatility', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('benchmark_return', sa.Float(), nullable=True),
    sa.Column('daily_values', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('monthly_returns', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('drawdown_series', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('benchmark_values', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['index_id'], ['indices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtests_index_id'), 'backtests', ['index_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('index_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('parent_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['index_id'], ['indices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('embed_widgets',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('index_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('owner_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('widget_type', sa.String(length=20), nullable=False),
    sa.Column('embed_token', sa.String(length=64), nullable=False),
    sa.Column('width', sa.String(length=20), nullable=False),
    sa.Column('height', sa.String(length=20), nullable=False),
    sa.Column('theme', sa.String(length=20), nullable=False),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('background_color', sa.String(length=7), nullable=True),
    sa.Column('font_family', sa.String(length=100), nullable=True),
    sa.Column('hide_branding', sa.Boolean(), nullable=False),
    sa.Column('chart_type', sa.String(length=20), nullable=False),
    sa.Column('show_volume', sa.Boolean(), nullable=False),
    sa.Column('show_legend', sa.Boolean(), nullable=False),
    sa.Column('default_period', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('allowed_domains', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('embed_count', sa.Integer(), nullable=False),
    sa.Column('last_embedded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['index_id'], ['indices.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embed_widgets_embed_token'), 'embed_widgets', ['embed_token'], unique=True)
    op.create_table('generated_reports',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('index_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('owner_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('template_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('report_type', sa.String(length=20), nullable=False),
    sa.Column('report_format', sa.String(length=10), nullable=False),
    sa.Column('as_of_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('metrics_snapshot', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('public_token', sa.String(length=64), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['index_id'], ['indices.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['report_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_reports_public_token'), 'generated_reports', ['public_token'], unique=False)
    op.create_table('index_components',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('index_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('avg_volume', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('target_weight', sa.Float(), nullable=True),
    sa.Column('shares', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('added_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('removed_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['index_id'], ['indices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_index_components_index_id'), 'index_components', ['index_id'], unique=False)
    op.create_index(op.f('ix_index_components_ticker'), 'index_components', ['ticker'], unique=False)
    op.create_table('index_corporate_action_logs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('index_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('corporate_action_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('action_taken', sa.Text(), nullable=False),
    sa.Column('old_weight', sa.Float(), nullable=True),
    sa.Column('new_weight', sa.Float(), nullable=True),
    sa.Column('old_shares', sa.Float(), nullable=True),
    sa.Column('new_shares', sa.Float(), nullable=True),
    sa.Column('adjustment_factor', sa.Float(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['corporate_action_id'], ['corporate_actions.id'], ),
    sa.ForeignKeyConstraint(['index_id'], ['indices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('index_snapshots',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('index_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('daily_return', sa.Float(), nullable=True),
    sa.Column('component_weights', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_rebalance_day', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['index_id'], ['indices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_index_snapshots_date'), 'index_snapshots', ['date'], unique=False)
    op.create_index(op.f('ix_index_snapshots_index_id'), 'index_snapshots', ['index_id'], unique=False)
    op.create_table('public_shares',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('index_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('owner_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('show_chart', sa.Boolean(), nullable=False),
    sa.Column('show_components', sa.Boolean(), nullable=False),
    sa.Column('show_performance', sa.Boolean(), nullable=False),
    sa.Column('show_factsheet', sa.Boolean(), nullable=False),
    sa.Column('allow_download', sa.Boolean(), nullable=False),
    sa.Column('title_override', sa.String(length=255), nullable=True),
    sa.Column('description_override', sa.Text(), nullable=True),
    sa.Column('theme', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('allowed_domains', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('last_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['index_id'], ['indices.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_public_shares_slug'), 'public_shares', ['slug'], unique=True)
    op.create_table('backtest_results',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('backtest_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('portfolio_value', sa.Float(), nullable=False),
    sa.Column('daily_return', sa.Float(), nullable=False),
    sa.Column('cumulative_return', sa.Float(), nullable=False),
    sa.Column('drawdown', sa.Float(), nullable=False),
    sa.Column('benchmark_value', sa.Float(), nullable=True),
    sa.Column('benchmark_return', sa.Float(), nullable=True),
    sa.Column('excess_return', sa.Float(), nullable=True),
    sa.Column('holdings', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_results_backtest_id'), 'backtest_results', ['backtest_id'], unique=False)
    op.create_index(op.f('ix_backtest_results_date'), 'backtest_results', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_backtest_results_date'), table_name='backtest_results')
    op.drop_index(op.f('ix_backtest_results_backtest_id'), table_name='backtest_results')
    op.drop_table('backtest_results')
    op.drop_index(op.f('ix_public_shares_slug'), table_name='public_shares')
    op.drop_table('public_shares')
    op.drop_index(op.f('ix_index_snapshots_index_id'), table_name='index_snapshots')
    op.drop_index(op.f('ix_index_snapshots_date'), table_name='index_snapshots')
    op.drop_table('index_snapshots')
    op.drop_table('index_corporate_action_logs')
    op.drop_index(op.f('ix_index_components_ticker'), table_name='index_components')
    op.drop_index(op.f('ix_index_components_index_id'), table_name='index_components')
    op.drop_table('index_components')
    op.drop_index(op.f('ix_generated_reports_public_token'), table_name='generated_reports')
    op.drop_table('generated_reports')
    op.drop_index(op.f('ix_embed_widgets_embed_token'), table_name='embed_widgets')
    op.drop_table('embed_widgets')
    op.drop_table('comments')
    op.drop_index(op.f('ix_backtests_index_id'), table_name='backtests')
    op.drop_table('backtests')
    op.drop_table('project_memberships')
    op.drop_index(op.f('ix_indices_project_id'), table_name='indices')
    op.drop_index(op.f('ix_indices_owner_id'), table_name='indices')
    op.drop_index(op.f('ix_indices_identifier'), table_name='indices')
    op.drop_table('indices')
    op.drop_index(op.f('ix_custom_securities_ticker'), table_name='custom_securities')
    op.drop_index(op.f('ix_custom_securities_data_source_id'), table_name='custom_securities')
    op.drop_table('custom_securities')
    op.drop_index(op.f('ix_activities_created_at'), table_name='activities')
    op.drop_table('activities')
    op.drop_table('webhook_endpoints')
    op.drop_table('sftp_destinations')
    op.drop_table('report_templates')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('organization_memberships')
    op.drop_index(op.f('ix_organization_invitations_token'), table_name='organization_invitations')
    op.drop_table('organization_invitations')
    op.drop_table('email_subscriptions')
    op.drop_index(op.f('ix_custom_data_sources_owner_id'), table_name='custom_data_sources')
    op.drop_table('custom_data_sources')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_table('delivery_logs')
    op.drop_index(op.f('ix_corporate_actions_ticker'), table_name='corporate_actions')
    op.drop_index(op.f('ix_corporate_actions_effective_date'), table_name='corporate_actions')
    op.drop_table('corporate_actions')
    # ### end Alembic commands ###

