"""Add stripe fields to user

Revision ID: 98f26ea4f190
Revises: 3baffa313307
Create Date: 2026-01-29 00:57:23.868046

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "98f26ea4f190"
down_revision: Union[str, None] = "3baffa313307"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("stripe_customer_id", sa.String(length=255), nullable=True))
    op.add_column("users", sa.Column("subscription_id", sa.String(length=255), nullable=True))
    op.add_column("users", sa.Column("subscription_status", sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "subscription_status")
    op.drop_column("users", "subscription_id")
    op.drop_column("users", "stripe_customer_id")
    # ### end Alembic commands ###
