"""Add guideline document and selection criteria to Index

Revision ID: 3baffa313307
Revises: 23a655966954
Create Date: 2026-01-28 21:27:31.068339

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3baffa313307"
down_revision: Union[str, None] = "23a655966954"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("indices", sa.Column("guideline_file_path", sa.Text(), nullable=True))
    op.add_column("indices", sa.Column("guideline_file_url", sa.Text(), nullable=True))
    op.add_column("indices", sa.Column("guideline_file_name", sa.String(length=255), nullable=True))
    op.add_column(
        "indices",
        sa.Column("selection_criteria", postgresql.JSON(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("indices", "selection_criteria")
    op.drop_column("indices", "guideline_file_name")
    op.drop_column("indices", "guideline_file_url")
    op.drop_column("indices", "guideline_file_path")
    # ### end Alembic commands ###
